langauge: java
jdk:
  - openjdk14

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install: # ./gradlew Permission denied 방지
  - chmod +x gradlew

# CI 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - sheepserverdown@gmail.com
